spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myapp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource

  mybatis-plus:
    mapper-locations: com/mysprb/mysprb/mappers/*.xml
    type-aliases-package: com.mysprb.mysprb.domain
