spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myapp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
      cache: false
      check-template: true
      check-template-location: true
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5

  mybatis-plus:
    mapper-locations: com/mysprb/mysprb/mappers/*.xml
    type-aliases-package: com.mysprb.mysprb.domain
