spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myapp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
      cache: false
      check-template: true
      check-template-location: true
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      mode: HTML5
      servlet:
        content-type: text/html

  mybatis-plus:
    mapper-locations: com/mysprb/mysprb/mappers/*.xml
    type-aliases-package: com.mysprb.mysprb.domain



#测试访问配置文件
#mybean:
#  main-name: 中二拯救世界
#  id: 11111
#  flag: false
#  birthday: 2020/7/19
#  map:
#    ss: 魔王
#    skill: 魔王幻影弹
#  list:
#    - p1
#    - p2
#    - p3
#  p:
#    name: 义彦
#    age: 18


